name: null
favicon: null
layout_spectrum: 0.97586
typography_spectrum: 0.24977
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f4f3'
    - '#171e0e'
    - '#5f698c'
    - '#aca7c7'
    - '#b06665'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
