name: null
favicon: null
layout_spectrum: 0.48276
typography_spectrum: 0.4739
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ddd2b7'
    - '#9f8d78'
    - '#131925'
    - '#696961'
    - '#394345'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
